export const UPDATE_RAW_TRAFFIC_DATA = 'UPDATE_RAW_TRAFFIC_DATA';
export type UPDATE_RAW_TRAFFIC_DATA = typeof UPDATE_RAW_TRAFFIC_DATA;

export const UPDATE_AVG_TRAFFIC_DATA = 'UPDATE_AVG_TRAFFIC_DATA';
export type UPDATE_AVG_TRAFFIC_DATA = typeof UPDATE_AVG_TRAFFIC_DATA;
