export const CHANGE_TEST_TEXT = 'CHANGE_TEST_TEXT';
export type CHANGE_TEST_TEXT = typeof CHANGE_TEST_TEXT;

export const UPDATE_RAW_TRAFFIC_DATA = 'UPDATE_RAW_TRAFFIC_DATA';
export type UPDATE_RAW_TRAFFIC_DATA = typeof UPDATE_RAW_TRAFFIC_DATA;
